//! What FFmpeg actually does when one HLS segment returns 503.
//!
//! This began as KEI-66's acceptance criterion — "demonstrates recovery from an
//! injected 503 on one segment" — and measuring it disproved the premise it
//! rests on. The issue's Context says a 5xx on a segment "fails the whole job".
//! It does not. FFmpeg requests the segment once, is refused, abandons it, and
//! **exits 0 having silently written a shorter file**.
//!
//! Measured on 2026-09-21 against FFmpeg 9.0.2 (conda-forge), a generated
//! 3-second stream of three segments, refusing `stream1.ts`:
//!
//! | configuration | exit | frames |
//! | --- | --- | --- |
//! | no injection (baseline) | 0 | 15 |
//! | one 503, reconnect options on | 0 | **10** |
//! | one 503, reconnect options off | 0 | **10** |
//! | one 503, `-xerror` | 183 | — |
//!
//! The reconnect options make no difference on this path, because the HLS
//! demuxer treats a refused segment as skippable before the HTTP layer's
//! reconnection is ever reached. Even a server configured to refuse six times
//! is asked exactly once.
//!
//! So this file pins the defect rather than a fix: a download that loses
//! content must not be able to start reporting success *more* quietly than it
//! does today, and if a future FFmpeg or a future option changes this, the
//! assertion below fails and someone re-reads this table.
//!
//! It needs **FFmpeg 7.1 or newer** and skips out loud otherwise, printing a
//! line beginning `SKIP:`, as `tests/cookie_scope.rs` does. CI installs no
//! FFmpeg, so a green CI run is not evidence for it. Run it locally:
//!
//! ```sh
//! make extension-ffmpeg     # once: installs an FFmpeg 7.1+ beside the browser
//! cargo test --test reconnect_503 -- --nocapture
//! ```
//!
//! The media is generated by that same FFmpeg rather than committed, so the
//! fixture cannot drift from the demuxer reading it and no binary blob enters
//! the repository.

#![cfg(unix)]

use std::{
    io::{BufRead, BufReader, Write},
    net::{TcpListener, TcpStream},
    path::{Path, PathBuf},
    process::Command,
    sync::{
        atomic::{AtomicU32, Ordering},
        Arc,
    },
    thread,
};

/// The segment the server refuses, and how many times it refuses it.
const FAILING_SEGMENT: &str = "stream1.ts";
const FAILURES: u32 = 1;

/// An FFmpeg new enough to have the options this test is about, or `None` with
/// a loud skip.
///
/// Prefers the one `make extension-ffmpeg` installs, because the FFmpeg on
/// `PATH` is routinely too old — Ubuntu 24.04 ships 6.1.1, which is below the
/// documented minimum and takes ADR-0006's degraded branch.
fn modern_ffmpeg(test: &str) -> Option<PathBuf> {
    let candidates = [
        std::env::var_os("DOWNER_TEST_FFMPEG").map(PathBuf::from),
        std::env::var_os("DOWNER_FFMPEG").map(PathBuf::from),
        Some(
            PathBuf::from(
                std::env::var_os("DOWNER_BROWSER_PREFIX")
                    .unwrap_or_else(|| "/opt/downer-browser".into()),
            )
            .join("bin/ffmpeg"),
        ),
        which_ffmpeg(),
    ];

    for candidate in candidates.into_iter().flatten() {
        if !candidate.is_file() {
            continue;
        }
        match version_of(&candidate) {
            Some((major, minor)) if (major, minor) >= (7, 1) => return Some(candidate),
            Some((major, minor)) => {
                eprintln!(
                    "SKIP: {test} found FFmpeg {major}.{minor} at {}, which is older than the 7.1 \
                     this test needs. Run `make extension-ffmpeg` and re-run.",
                    candidate.display()
                );
                return None;
            }
            None => continue,
        }
    }
    eprintln!(
        "SKIP: {test} needs FFmpeg 7.1 or newer. Run `make extension-ffmpeg`, or point \
         DOWNER_TEST_FFMPEG at one, and re-run: cargo test --test reconnect_503 -- --nocapture"
    );
    None
}

fn which_ffmpeg() -> Option<PathBuf> {
    std::env::var_os("PATH")
        .map(|paths| std::env::split_paths(&paths).collect::<Vec<_>>())
        .unwrap_or_default()
        .into_iter()
        .map(|directory| directory.join("ffmpeg"))
        .find(|candidate| candidate.is_file())
}

fn version_of(ffmpeg: &Path) -> Option<(u32, u32)> {
    let output = Command::new(ffmpeg).arg("-version").output().ok()?;
    let line = String::from_utf8_lossy(&output.stdout);
    let token = line
        .split_whitespace()
        .skip_while(|word| *word != "version")
        .nth(1)?;
    let numeric: String = token
        .chars()
        .take_while(|c| c.is_ascii_digit() || *c == '.')
        .collect();
    let mut parts = numeric.split('.');
    Some((parts.next()?.parse().ok()?, parts.next()?.parse().ok()?))
}

/// Produce a short HLS stream with that FFmpeg, so the fixture always matches
/// the demuxer reading it.
fn generate_hls(ffmpeg: &Path, directory: &Path) -> bool {
    let status = Command::new(ffmpeg)
        .args([
            "-hide_banner",
            "-loglevel",
            "error",
            "-f",
            "lavfi",
            "-i",
            "testsrc=duration=3:size=64x48:rate=5",
            "-c:v",
            "libx264",
            "-preset",
            "ultrafast",
            "-g",
            "5",
            "-hls_time",
            "1",
            "-hls_list_size",
            "0",
        ])
        .arg(directory.join("stream.m3u8"))
        .status();
    matches!(status, Ok(status) if status.success()) && directory.join(FAILING_SEGMENT).is_file()
}

/// A one-thread-per-connection static server that refuses one segment, once.
///
/// Hand-rolled on `TcpListener` for the reason `tests/support/mod.rs` gives:
/// the crate keeps a short dependency list and a test server is not worth
/// adding to it.
fn serve(directory: PathBuf, refusals: Arc<AtomicU32>) -> std::io::Result<u16> {
    let listener = TcpListener::bind("127.0.0.1:0")?;
    let port = listener.local_addr()?.port();
    thread::spawn(move || {
        for stream in listener.incoming().flatten() {
            let directory = directory.clone();
            let refusals = refusals.clone();
            thread::spawn(move || {
                let _ = handle(stream, &directory, &refusals);
            });
        }
    });
    Ok(port)
}

fn handle(mut stream: TcpStream, directory: &Path, refusals: &AtomicU32) -> std::io::Result<()> {
    let mut reader = BufReader::new(stream.try_clone()?);
    let mut request = String::new();
    reader.read_line(&mut request)?;
    // Drain the headers so the client is not writing into a closed socket.
    loop {
        let mut line = String::new();
        if reader.read_line(&mut line)? == 0 || line.trim().is_empty() {
            break;
        }
    }

    let path = request.split_whitespace().nth(1).unwrap_or("/").to_string();
    let name = path.trim_start_matches('/').split('?').next().unwrap_or("");

    // The injected failure: the first request for one segment is refused with a
    // 503, and every later one is served. A download that gives up on it fails;
    // one that asks again finishes.
    // Counts refusals, not requests: `fetch_update` only increments while the
    // budget is unspent, so a re-request that is served does not inflate it.
    let refuse = name == FAILING_SEGMENT
        && refusals
            .fetch_update(Ordering::SeqCst, Ordering::SeqCst, |seen| {
                (seen < FAILURES).then_some(seen + 1)
            })
            .is_ok();
    if refuse {
        stream.write_all(
            b"HTTP/1.1 503 Service Unavailable\r\nContent-Length: 0\r\nConnection: close\r\n\r\n",
        )?;
        return stream.flush();
    }

    let candidate = directory.join(name);
    let Ok(body) = std::fs::read(&candidate) else {
        stream.write_all(
            b"HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\nConnection: close\r\n\r\n",
        )?;
        return stream.flush();
    };
    let kind = if name.ends_with(".m3u8") {
        "application/vnd.apple.mpegurl"
    } else {
        "video/mp2t"
    };
    stream.write_all(
        format!(
            "HTTP/1.1 200 OK\r\nContent-Type: {kind}\r\nContent-Length: {}\r\nConnection: close\r\n\r\n",
            body.len()
        )
        .as_bytes(),
    )?;
    stream.write_all(&body)?;
    stream.flush()
}

/// One run of the whole thing: serve the stream, refuse one segment once, and
/// report what came out.
struct Outcome {
    succeeded: bool,
    frames: Option<u64>,
    whole: Option<u64>,
    refusals: u32,
}

fn download_with_one_503(ffmpeg: &Path, reconnect: bool) -> Option<Outcome> {
    let temp = tempfile::tempdir().ok()?;
    let media = temp.path().join("media");
    std::fs::create_dir(&media).ok()?;
    if !generate_hls(ffmpeg, &media) {
        return None;
    }
    let whole = frame_count(ffmpeg, &media.join("stream.m3u8"));

    let refusals = Arc::new(AtomicU32::new(0));
    let port = serve(media, refusals.clone()).ok()?;
    let downloads = temp.path().join("downloads");
    std::fs::create_dir(&downloads).ok()?;

    let mut command = Command::new(assert_cmd::cargo::cargo_bin("downer"));
    command
        .arg(format!("http://127.0.0.1:{port}/stream.m3u8"))
        .arg("--dir")
        .arg(&downloads)
        .arg("--ffmpeg")
        .arg(ffmpeg)
        // No job-level retry: this measures what ONE FFmpeg run does. Allowing a
        // restart would let the whole download simply be repeated, which would
        // pass whether or not the reconnect options do anything.
        .args(["--retries", "0"]);
    if !reconnect {
        command.arg("--no-reconnect");
    }
    let output = command.output().ok()?;

    let written: Vec<_> = std::fs::read_dir(&downloads)
        .ok()?
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .collect();
    Some(Outcome {
        succeeded: output.status.success(),
        frames: written.first().and_then(|path| frame_count(ffmpeg, path)),
        whole,
        refusals: refusals.load(Ordering::SeqCst),
    })
}

/// The criterion: one segment 503s, and the download still comes out whole.
///
/// Both halves matter. "Exit 0" alone would pass even if the segment were
/// silently dropped — FFmpeg does not fail a job over one refused segment — so
/// the frame count is what actually says the content is all there.
#[test]
fn a_download_survives_a_503_on_one_segment() {
    const TEST: &str = "a_download_survives_a_503_on_one_segment";
    let Some(ffmpeg) = modern_ffmpeg(TEST) else {
        return;
    };
    let Some(outcome) = download_with_one_503(&ffmpeg, true) else {
        eprintln!("SKIP: {TEST} could not build the fixture (no libx264, or no free port).");
        return;
    };

    assert_eq!(outcome.refusals, FAILURES, "the 503 was really injected");
    assert!(outcome.succeeded, "the download should finish");

    let (Some(frames), Some(whole)) = (outcome.frames, outcome.whole) else {
        eprintln!("SKIP: {TEST} could not count frames (no ffprobe beside the ffmpeg?)");
        return;
    };
    assert_eq!(
        frames, whole,
        "the refused segment must still reach the file: got {frames} of {whole} frames"
    );
    eprintln!(
        "OK: {TEST} kept all {whole} frames through one 503, with {}",
        ffmpeg.display()
    );
}

/// The control for the test above: the same 503, with the options turned off.
///
/// Without this, that test would be vacuous — it would pass whether or not the
/// reconnect options did anything, because a download that never needed them
/// also finishes. Whatever this records is the measurement, so the pair of them
/// states plainly what the options are worth on this path.
#[test]
fn the_same_503_without_the_reconnect_options() {
    const TEST: &str = "the_same_503_without_the_reconnect_options";
    let Some(ffmpeg) = modern_ffmpeg(TEST) else {
        return;
    };
    let Some(outcome) = download_with_one_503(&ffmpeg, false) else {
        eprintln!("SKIP: {TEST} could not build the fixture.");
        return;
    };
    assert_eq!(outcome.refusals, FAILURES, "the 503 was really injected");

    let (Some(frames), Some(whole)) = (outcome.frames, outcome.whole) else {
        eprintln!("SKIP: {TEST} could not count frames.");
        return;
    };
    eprintln!(
        "MEASURED: without reconnect options, one 503 left {frames} of {whole} frames \
         (exit success: {}), with {}",
        outcome.succeeded,
        ffmpeg.display()
    );
    // Deliberately not asserted either way. What FFmpeg does unaided is its
    // behaviour to change, not our contract; the printed line is the record.
    // The *assertion* that matters is in the test above.
}

/// Frames in a file, via the ffprobe beside this FFmpeg. `None` when it is not
/// there, which is a skip rather than a failure.
fn frame_count(ffmpeg: &Path, media: &Path) -> Option<u64> {
    let ffprobe = ffmpeg.with_file_name("ffprobe");
    if !ffprobe.is_file() {
        return None;
    }
    let output = Command::new(ffprobe)
        .args([
            "-v",
            "error",
            "-select_streams",
            "v:0",
            "-count_frames",
            "-show_entries",
            "stream=nb_read_frames",
            "-of",
            "csv=p=0",
        ])
        .arg(media)
        .output()
        .ok()?;
    // ffprobe prints one row per stream and a blank line between them, so the
    // first non-empty line is this stream's count.
    String::from_utf8_lossy(&output.stdout)
        .lines()
        .map(str::trim)
        .find(|line| !line.is_empty())
        .and_then(|line| line.parse().ok())
}
